global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

prometheus:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  retention: 7d 
  replicas: 1 


alertmanager:
  enabled: false 

nodeExporter:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

kubeStateMetrics:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

prometheusOperator:
  enabled: true
  replicas: 1 